// GENERATED by scripts/gen-mascot-manifest.mjs — do not edit by hand.
// Maps a mascot slug to its illustration under public/. Slugs absent here fall
// back to the vector art in components/ui/mascot.tsx.

import type { MascotSlug } from "@/lib/gamification/level";

export const MASCOT_ART: Partial<Record<MascotSlug, string>> = {
  hiyoko: "/mascots/hiyoko.webp",
  hoo: "/mascots/hoo.webp",
  kame: "/mascots/kame.webp",
  kitsune: "/mascots/kitsune.webp",
  manekineko: "/mascots/manekineko.webp",
  ryu: "/mascots/ryu.webp",
  saru: "/mascots/saru.webp",
  shika: "/mascots/shika.webp",
  shishi: "/mascots/shishi.webp",
  tanuki: "/mascots/tanuki.webp",
  tengu: "/mascots/tengu.webp",
  tora: "/mascots/tora.webp",
  tsuru: "/mascots/tsuru.webp",
  usagi: "/mascots/usagi.webp",
};
